name: Docker Image CD

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Git tag name
        id: git-tag
        run: echo ::set-output name=TAG_NAME::$(git describe --tags --abbrev=0)

      - name: Get Git commit hash
        id: git-commit
        run: echo ::set-output name=COMMIT_HASH::$(git rev-parse HEAD)

      - name: Generate Docker tags
        id: docker-tags
        uses: docker/metadata-action@v3
        with:
          images: docker.io/calzada4/proj5
          tags: |
            latest
            ${{ steps.git-tag.outputs.TAG_NAME }}
            ${{ steps.git-commit.outputs.COMMIT_HASH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker-tags.outputs.tags }}
